# cricket 

In [2]:
import numpy as np #for arrays
import pandas as pd #for importing and managing datasets
import pickle #for saving the model
from sklearn.model_selection import train_test_split #for splitting the dataset
from sklearn.neighbors import KNeighborsClassifier #for KNN model
from sklearn.metrics import confusion_matrix #for confusion matrix

In [32]:

data = pd.read_csv(r'C:\Users\user\Downloads\odm.csv',engine='python',sep='::')


In [33]:
data

version,1.3.0
0                                    info,team,Bahamas
1                                    info,team,Bermuda
2                                     info,gender,male
3                                     info,season,2010
4                                 info,date,2010/05/28
..                                                 ...
481  ball,2,27.4,Bermuda,JJ Tucker,DL Hemp,NH Ekana...
482  ball,2,27.5,Bermuda,DL Hemp,JJ Tucker,NH Ekana...
483  ball,2,27.6,Bermuda,DL Hemp,JJ Tucker,NH Ekana...
484  ball,2,28.1,Bermuda,JJ Tucker,DL Hemp,JR Barry...
485  ball,2,28.2,Bermuda,JJ Tucker,DL Hemp,JR Barry...

[486 rows x 1 columns]

In [35]:
data.head()

version,1.3.0
0     info,team,Bahamas
1     info,team,Bermuda
2      info,gender,male
3      info,season,2010
4  info,date,2010/05/28

In [36]:
data.shape

(486, 1)

In [39]:
data.describe()

version,1.3.0
count                                                 486
unique                                                486
top     ball,1,9.4,Bahamas,GT Taylor,H Gilliard,K Tuck...
freq                                                    1

In [42]:
X = np.zeros((486,132),dtype='float64')
X[:,486:132]=data.iloc[:,4:6].values

Y = data.iloc[:,-1].values

In [43]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
Y

array(['info,team,Bahamas', 'info,team,Bermuda', 'info,gender,male',
       'info,season,2010', 'info,date,2010/05/28',
       'info,competition,ICC World Cricket League Americas Region Division One 2010',
       'info,venue,National Stadium', 'info,city,Hamilton',
       'info,toss_winner,Bermuda', 'info,toss_decision,field',
       'info,player_of_match,K Tucker', 'info,umpire,H Smythe',
       'info,umpire,K Bayney', 'info,reserve_umpire,R Austin',
       'info,match_referee,AFG Griffith', 'info,winner,Bermuda',
       'info,winner_wickets,7',
       'ball,1,0.1,Bahamas,M Taylor,H Gilliard,MO Jones,0,0,"",""',
       'ball,1,0.2,Bahamas,M Taylor,H Gilliard,MO Jones,0,0,caught,M Taylor',
       'ball,1,0.3,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""',
       'ball,1,0.4,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""',
       'ball,1,0.5,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""',
       'ball,1,0.6,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""',
       'ball,1,1.1,Bahama

In [22]:
from sklearn.linear_model import LinearRegression

In [26]:
Y.reshape((-1,1))


array([['version,1.3.0'],
       ['info,team,Bahamas'],
       ['info,team,Bermuda'],
       ['info,gender,male'],
       ['info,season,2010'],
       ['info,date,2010/05/28'],
       ['info,competition,ICC World Cricket League Americas Region Division One 2010'],
       ['info,venue,National Stadium'],
       ['info,city,Hamilton'],
       ['info,toss_winner,Bermuda'],
       ['info,toss_decision,field'],
       ['info,player_of_match,K Tucker'],
       ['info,umpire,H Smythe'],
       ['info,umpire,K Bayney'],
       ['info,reserve_umpire,R Austin'],
       ['info,match_referee,AFG Griffith'],
       ['info,winner,Bermuda'],
       ['info,winner_wickets,7'],
       ['ball,1,0.1,Bahamas,M Taylor,H Gilliard,MO Jones,0,0,"",""'],
       ['ball,1,0.2,Bahamas,M Taylor,H Gilliard,MO Jones,0,0,caught,M Taylor'],
       ['ball,1,0.3,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""'],
       ['ball,1,0.4,Bahamas,RA Tappin,H Gilliard,MO Jones,0,0,"",""'],
       ['ball,1,0.5,Bahamas,RA Tappin,H

In [46]:
X.shape
X.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [68]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)


In [72]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=3)

In [76]:
knnmodel=KNeighborsClassifier(n_neighbors=3)

In [78]:
knnmodel.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [79]:
Y_predict1=knnmodel.predict(X_test)

In [82]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_predict1)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [87]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(Y_test,Y_predict1)
acc

0.0